image: Visual Studio 2017 Preview
version: 0.0.{build}
configuration:
  - Release

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet restore -v minimal

build:
  project: code-timer.sln
  parallel: true
  verbosity: minimal

test_script: 
  - dotnet test test\codetimer.tests

after_build:
  - dotnet pack ./src/codetimer/codetimer.csproj -o artifacts

artifacts:
  - path: src\codetimer\artifacts\*.nupkg
