image: Visual Studio 2017 Preview
version: 0.0.{build}
configuration:
  - Release

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet restore -v minimal

build:
  - dotnet build

test_script: 
  - dotnet test test\codetimer.tests --no-build

after_build:
  - dotnet pack ./src/codetimer/codetimer.csproj -o artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: src\codetimer\artifacts\*.nupkg

deploy:
  - provider: NuGet
    api_key:
    secure: OGU5pdzFVnLMi4Ux7Z4anszyUd7n+tzVdVbEBjcYHe3TC0XRNRveijFnTsPhcKmP
    skip_symbols: true
  on:
    branch: /^(master|dev)$/
