image: Visual Studio 2017 Preview
version: 0.0.{build}
configuration:
  - Release

environment:
  nuget_apikey:
    secure: xOqFq+QxPdWk98gstiJzC2R+6LC3GSwXs3P+tMniwDAMUzk+LFJvD4YSPbJePAqhgoovduOZuLPNn8qtmGO5WlLcGMh1uCxaMjfcU/ecxknD+a6i9GIl6vTrybX+cHimtkEhs/vGTBHEW1dPuc+ZRoLcljE8/+oKCuonq+DyB7mL8GFkudsyAEn4ufy1RUQZCj+XoT/ATiNiEIj0lPkaQL6gfBaf+5iBWhT8rvUxAefZZ5Q9qXxX0eSX/AWVDJamw72CXZ2+0vOfYVofEHDDTncNU+eIK2ZM2fY7Ow8S+nygyr3s831nhmJje/v1d875gLsfWvy6rsVO8Gr/ufE/D/2V6CiZ2DY9Y3fFLlPyK6SNcKwB5mwJKNN+a1g9+fu+0ZhKLsTaJ8lqjLLjxtYoqy5nsl6KdvW6BzgDLx9rkYBCF2s1zdb3y+HDYlEK0CnPxY8d8uVBo2mzN4WJceMqPB4UlanuejOj2SJ4yeFOQHA=

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet restore -v minimal

build:
  project: code-timer.sln
  parallel: true
  verbosity: minimal

test_script: 
  - dotnet test test\codetimer.tests

after_build:
  - dotnet pack ./src/codetimer/codetimer.csproj -o artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: src\codetimer\artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://api.nuget.org/v3/index.json
    api_key:
      secure: xOqFq+QxPdWk98gstiJzC2R+6LC3GSwXs3P+tMniwDAMUzk+LFJvD4YSPbJePAqhgoovduOZuLPNn8qtmGO5WlLcGMh1uCxaMjfcU/ecxknD+a6i9GIl6vTrybX+cHimtkEhs/vGTBHEW1dPuc+ZRoLcljE8/+oKCuonq+DyB7mL8GFkudsyAEn4ufy1RUQZCj+XoT/ATiNiEIj0lPkaQL6gfBaf+5iBWhT8rvUxAefZZ5Q9qXxX0eSX/AWVDJamw72CXZ2+0vOfYVofEHDDTncNU+eIK2ZM2fY7Ow8S+nygyr3s831nhmJje/v1d875gLsfWvy6rsVO8Gr/ufE/D/2V6CiZ2DY9Y3fFLlPyK6SNcKwB5mwJKNN+a1g9+fu+0ZhKLsTaJ8lqjLLjxtYoqy5nsl6KdvW6BzgDLx9rkYBCF2s1zdb3y+HDYlEK0CnPxY8d8uVBo2mzN4WJceMqPB4UlanuejOj2SJ4yeFOQHA=
    artifact: /.*\.nupkg/