image: Visual Studio 2017 Preview
version: 0.0.{build}
configuration:
  - Release

environment:
  nuget_apikey:
    secure: OGU5pdzFVnLMi4Ux7Z4anszyUd7n+tzVdVbEBjcYHe3TC0XRNRveijFnTsPhcKmP

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet restore -v minimal

build:
  project: code-timer.sln
  parallel: true
  verbosity: minimal

test_script: 
  - dotnet test test\codetimer.tests

after_build:
  - dotnet pack ./src/codetimer/codetimer.csproj -o artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: src\codetimer\artifacts\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: $env:nuget_apikey
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
