image: Visual Studio 2017 Preview
version: 0.0.{build}
configuration:
  - Release

environment:
  nuget_apikey:
    secure: LHjBpcjYVeJAQebGvBVylvxvN6aHuRxK2p94/Iqpb8AedXQCJobFJP1Ii0hmWZ6w

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet restore -v minimal

build:
  project: code-timer.sln
  parallel: true
  verbosity: minimal

test_script: 
  - dotnet test test\codetimer.tests

after_build:
  - dotnet pack ./src/codetimer/codetimer.csproj -o artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: src\codetimer\artifacts\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: $env:nuget_apikey
  skip_symbols: true
  on:
    branch: /^(master|dev)$/

#deploy_script:
# - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
# - ps: .\nuget.exe setApiKey $env:nuget_apikey -source https://www.nuget.org | out-null
# - ps: ($artifacts.values | Where-Object { $_.path -like '*.nupkg' }) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package}
